services:
  - type: web
    name: soccer-result-predictor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir "Soccer Predictor/Website" app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.6
      - key: API_RATE_LIMIT_PER_MINUTE
        value: 60
